name: Build Container
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  install_buildtools:
    runs-on: windows-latest
    steps:
      - name: Install buildtools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_BuildTools.exe
          cmd /S /C "start /w vs_BuildTools.exe --nocache --noUpdateInstaller --installPath %cd%\vs_buildtools --addProductLang en-US --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --wait --quiet"

      - name: Compress buildtools
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: vs_buildtools
          pathTarget: vs_buildtools.7z

      - name: Publish buildtools artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: BuildTools
          path: vs_buildtools.7z
            
  build_container:
    needs: install_buildtools
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
    
      - name: Download buildtools artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: BuildTools
          path: vs_buildtools.7z
          
      - name: Extract buildtools
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: vs_buildtools.7z
          pathTarget: vs_buildtools
    
      - name: test
        run: |
          pwd
          ls -al
    
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          no-cache: true
          tags: |
            ghcr.io/rektinator/msbuild-docker:${{ github.ref_name }}
            ghcr.io/rektinator/msbuild-docker:latest
    
