name: Build Container
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  install_buildtools:
    runs-on: windows-latest
    steps:
      - name: Install vs2022 buildtools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_BuildTools.exe
          cmd /S /C "start /w vs_BuildTools.exe --nocache --noUpdateInstaller --installPath %cd%\vs_buildtools --addProductLang en-US --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --wait --quiet"

      - name: Publish buildtools artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: BuildTools
          path: vs_buildtools
            
  build_container:
    needs: install_buildtools
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
    
      - name: Download buildtools artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: BuildTools
          path: vs_buildtools
    
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref.name }}
            ghcr.io/${{ github.repository }}:latest
    
